import type {
  Bid,
  Dispute,
  Message,
  Rating,
  Task,
  Transaction,
  User,
} from "./types";

const now = "2026-07-11T09:00:00.000Z";
const daysAgo = (n: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const CUSTOMERS: User[] = [
  {
    id: "cust-1",
    email: "nadeesha.p@gmail.com",
    name: "Nadeesha Perera",
    phone: "+94 77 210 4432",
    photo: "https://i.pravatar.cc/150?img=47",
    location: "Nugegoda, Colombo",
    userType: "customer",
    isStudent: false,
    createdAt: daysAgo(120),
  },
  {
    id: "cust-2",
    email: "ruwan.f@outlook.com",
    name: "Ruwan Fernando",
    phone: "+94 71 556 8821",
    photo: "https://i.pravatar.cc/150?img=12",
    location: "Peradeniya, Kandy",
    userType: "customer",
    isStudent: false,
    createdAt: daysAgo(200),
  },
  {
    id: "cust-3",
    email: "isuri.kumari@uoc.ac.lk",
    name: "Isuri Kumari",
    phone: "+94 76 344 9012",
    photo: "https://i.pravatar.cc/150?img=32",
    location: "Colombo 07",
    userType: "customer",
    isStudent: true,
    studentEmail: "isuri.kumari@uoc.ac.lk",
    studentVerifiedAt: daysAgo(80),
    createdAt: daysAgo(150),
  },
];

export const WORKERS: User[] = [
  {
    id: "work-1",
    email: "sunil.plumbing@gmail.com",
    name: "Sunil Jayasuriya",
    phone: "+94 77 890 1122",
    photo: "https://i.pravatar.cc/150?img=51",
    location: "Maharagama, Colombo",
    userType: "worker",
    isStudent: false,
    createdAt: daysAgo(400),
    workerProfile: {
      bio: "Licensed plumber with 12 years fixing everything from leaky taps to full bathroom re-piping. Same-day callouts across Colombo suburbs.",
      skills: ["plumbing", "appliance_repair"],
      yearsExperience: 12,
      portfolio: [
        "/placeholders/plumbing.png",
        "/placeholders/plumbing.png",
      ],
      rating: { avgStars: 4.9, totalReviews: 132, completedJobs: 141, noShowCount: 0, disputeCount: 0 },
      badges: { verified: true, reliability: true, trusted: true, pro: true },
      paymentMethods: [
        { type: "koko_pay", verified: true, label: "Koko Pay" },
        { type: "bank_transfer", verified: true, label: "Commercial Bank ****4521" },
      ],
      suspended: false,
      responseTimeMinutes: 14,
      completionRate: 0.99,
    },
  },
  {
    id: "work-2",
    email: "malithi.electric@gmail.com",
    name: "Malithi Wickramasinghe",
    phone: "+94 70 223 5567",
    photo: "https://i.pravatar.cc/150?img=45",
    location: "Kandy Town",
    userType: "worker",
    isStudent: false,
    createdAt: daysAgo(310),
    workerProfile: {
      bio: "Certified electrician (EIE registered). Wiring, panel upgrades, inverter/solar setup. Safety-first, receipts for every job.",
      skills: ["electrical"],
      yearsExperience: 8,
      portfolio: [
        "/placeholders/electrical.png",
      ],
      rating: { avgStars: 4.8, totalReviews: 94, completedJobs: 101, noShowCount: 1, disputeCount: 0 },
      badges: { verified: true, reliability: true, trusted: true, pro: false },
      paymentMethods: [{ type: "koko_pay", verified: true, label: "Koko Pay" }],
      suspended: false,
      responseTimeMinutes: 22,
      completionRate: 0.97,
    },
  },
  {
    id: "work-3",
    email: "kasun.paints@gmail.com",
    name: "Kasun Silva",
    phone: "+94 75 667 8890",
    photo: "https://i.pravatar.cc/150?img=13",
    location: "Dehiwala, Colombo",
    userType: "worker",
    isStudent: false,
    createdAt: daysAgo(90),
    workerProfile: {
      bio: "Interior & exterior painting, waterproofing, texture finishes. Free colour consultation with every quote.",
      skills: ["painting"],
      yearsExperience: 5,
      portfolio: [
        "/placeholders/painting.png",
        "/placeholders/painting.png",
      ],
      rating: { avgStars: 4.6, totalReviews: 41, completedJobs: 47, noShowCount: 0, disputeCount: 1 },
      badges: { verified: true, reliability: true, trusted: false, pro: false },
      paymentMethods: [{ type: "mobile_money", verified: true, label: "Dialog eZ Cash" }],
      suspended: false,
      responseTimeMinutes: 40,
      completionRate: 0.94,
    },
  },
  {
    id: "work-4",
    email: "tharindu.movers@gmail.com",
    name: "Tharindu & Team Movers",
    phone: "+94 77 112 3344",
    photo: "https://i.pravatar.cc/150?img=15",
    location: "Malabe, Colombo",
    userType: "worker",
    isStudent: false,
    createdAt: daysAgo(250),
    workerProfile: {
      bio: "4-man moving crew with a covered lorry. House shifting, office relocation, furniture assembly. Careful with fragile items.",
      skills: ["moving"],
      yearsExperience: 6,
      portfolio: [
        "/placeholders/moving.png",
      ],
      rating: { avgStars: 4.7, totalReviews: 76, completedJobs: 80, noShowCount: 0, disputeCount: 0 },
      badges: { verified: true, reliability: true, trusted: true, pro: false },
      paymentMethods: [
        { type: "koko_pay", verified: true, label: "Koko Pay" },
        { type: "cash_pickup", verified: true, label: "Cash on completion" },
      ],
      suspended: false,
      responseTimeMinutes: 18,
      completionRate: 0.98,
    },
  },
  {
    id: "work-5",
    email: "chamodi.clean@gmail.com",
    name: "Chamodi Rathnayake",
    phone: "+94 71 998 2210",
    photo: "https://i.pravatar.cc/150?img=48",
    location: "Rajagiriya, Colombo",
    userType: "worker",
    isStudent: true,
    studentEmail: "chamodi.r@sjp.ac.lk",
    studentVerifiedAt: daysAgo(60),
    createdAt: daysAgo(70),
    workerProfile: {
      bio: "Uni student doing deep-cleaning gigs on weekends. Kitchens, bathrooms, move-in/move-out cleans. Bring my own supplies.",
      skills: ["cleaning"],
      yearsExperience: 2,
      portfolio: [
        "/placeholders/cleaning.png",
      ],
      rating: { avgStars: 4.9, totalReviews: 28, completedJobs: 30, noShowCount: 0, disputeCount: 0 },
      badges: { verified: true, reliability: true, trusted: false, pro: false },
      paymentMethods: [{ type: "koko_pay", verified: true, label: "Koko Pay" }],
      suspended: false,
      responseTimeMinutes: 25,
      completionRate: 1.0,
    },
  },
  {
    id: "work-6",
    email: "nimal.carpentry@gmail.com",
    name: "Nimal Bandara",
    phone: "+94 76 445 7781",
    photo: "https://i.pravatar.cc/150?img=60",
    location: "Kadawatha, Gampaha",
    userType: "worker",
    isStudent: false,
    createdAt: daysAgo(500),
    workerProfile: {
      bio: "Custom furniture, built-in wardrobes, door/window repairs. 18 years in the trade, work all over Colombo & Gampaha.",
      skills: ["carpentry"],
      yearsExperience: 18,
      portfolio: [
        "/placeholders/carpentry.png",
      ],
      rating: { avgStars: 4.95, totalReviews: 210, completedJobs: 224, noShowCount: 0, disputeCount: 0 },
      badges: { verified: true, reliability: true, trusted: true, pro: true },
      paymentMethods: [{ type: "bank_transfer", verified: true, label: "Sampath Bank ****9012" }],
      suspended: false,
      responseTimeMinutes: 35,
      completionRate: 0.99,
    },
  },
  {
    id: "work-7",
    email: "asela.welds@gmail.com",
    name: "Asela Gunaratne",
    phone: "+94 70 667 1145",
    photo: "https://i.pravatar.cc/150?img=33",
    location: "Kelaniya, Colombo",
    userType: "worker",
    isStudent: false,
    createdAt: daysAgo(30),
    workerProfile: {
      bio: "Mobile welding for gates, grills, staircase railings. New workshop, competitive rates, quick turnaround.",
      skills: ["welding"],
      yearsExperience: 3,
      portfolio: [],
      rating: { avgStars: 4.2, totalReviews: 6, completedJobs: 6, noShowCount: 0, disputeCount: 0 },
      badges: { verified: true, reliability: false, trusted: false, pro: false },
      paymentMethods: [{ type: "cash_pickup", verified: true, label: "Cash on completion" }],
      suspended: false,
      responseTimeMinutes: 50,
      completionRate: 1.0,
    },
  },
  {
    id: "work-8",
    email: "dilani.garden@gmail.com",
    name: "Dilani Ekanayake",
    phone: "+94 77 334 5567",
    photo: "https://i.pravatar.cc/150?img=44",
    location: "Battaramulla, Colombo",
    userType: "worker",
    isStudent: false,
    createdAt: daysAgo(180),
    workerProfile: {
      bio: "Garden design, lawn maintenance, tree pruning. I also handle small landscaping jobs and irrigation fixes.",
      skills: ["gardening"],
      yearsExperience: 7,
      portfolio: [
        "/placeholders/gardening.png",
      ],
      rating: { avgStars: 4.5, totalReviews: 33, completedJobs: 36, noShowCount: 1, disputeCount: 0 },
      badges: { verified: true, reliability: false, trusted: false, pro: false },
      paymentMethods: [{ type: "koko_pay", verified: true, label: "Koko Pay" }],
      suspended: false,
      responseTimeMinutes: 60,
      completionRate: 0.92,
    },
  },
];

export const USERS: User[] = [...CUSTOMERS, ...WORKERS];

export const TASKS: Task[] = [
  {
    id: "task-1",
    title: "Fix leaking kitchen tap and replace washer",
    description:
      "The kitchen mixer tap has been dripping constantly for a week and the handle is loose. Need someone to replace the washer/cartridge, ideally today or tomorrow.",
    category: "plumbing",
    photos: ["/placeholders/plumbing.png"],
    location: { address: "45 Kirulapone Ave", city: "Nugegoda, Colombo", lat: 6.8721, lng: 79.8891 },
    budgetMin: 2000,
    budgetMax: 4000,
    timeline: "urgent",
    status: "open",
    customerId: "cust-1",
    completionPhotos: [],
    paymentStatus: "pending",
    paymentAmount: 0,
    platformFee: 0,
    workerAmount: 0,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-2",
    title: "Full house rewiring quote for 3-bedroom home",
    description:
      "Old house, wiring hasn't been touched in 20+ years. Want a full inspection and rewiring quote, plus a new distribution board with proper breakers.",
    category: "electrical",
    photos: ["/placeholders/electrical.png"],
    location: { address: "12 Lake Rd", city: "Kandy Town", lat: 7.2906, lng: 80.6337 },
    budgetMin: 40000,
    budgetMax: 70000,
    timeline: "flexible",
    status: "open",
    customerId: "cust-2",
    completionPhotos: [],
    paymentStatus: "pending",
    paymentAmount: 0,
    platformFee: 0,
    workerAmount: 0,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "task-3",
    title: "Paint living room + hallway (approx 400 sq ft)",
    description:
      "Need interior painting for living room and hallway. Walls need minor crack filling first. We'll supply paint colour preference after quote.",
    category: "painting",
    photos: ["/placeholders/painting.png"],
    location: { address: "78 Galle Rd", city: "Dehiwala, Colombo", lat: 6.8508, lng: 79.8654 },
    budgetMin: 15000,
    budgetMax: 25000,
    timeline: "scheduled",
    scheduledDate: "2026-07-20",
    status: "assigned",
    customerId: "cust-3",
    workerId: "work-3",
    completionPhotos: [],
    paymentStatus: "escrow",
    paymentAmount: 20000,
    platformFee: 4000,
    workerAmount: 16000,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(2),
  },
  {
    id: "task-4",
    title: "House shifting: 2-bedroom apartment to Malabe",
    description:
      "Moving from a 2nd floor apartment (no lift) to a ground floor house in Malabe. Includes a fridge, washing machine, sofa set, beds and ~15 boxes.",
    category: "moving",
    photos: ["/placeholders/moving.png"],
    location: { address: "22 Havelock Rd", city: "Colombo 05", lat: 6.8862, lng: 79.8621 },
    budgetMin: 12000,
    budgetMax: 18000,
    timeline: "scheduled",
    scheduledDate: "2026-07-15",
    status: "in_progress",
    customerId: "cust-1",
    workerId: "work-4",
    completionPhotos: [],
    paymentStatus: "escrow",
    paymentAmount: 15000,
    platformFee: 3000,
    workerAmount: 12000,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-5",
    title: "Deep clean 3-bedroom house before move-in",
    description:
      "Just bought the house, needs a full deep clean before we move in — kitchen, 2 bathrooms, all floors, windows inside and out.",
    category: "cleaning",
    photos: ["/placeholders/cleaning.png"],
    location: { address: "9 Elvitigala Mw", city: "Colombo 08", lat: 6.9059, lng: 79.8747 },
    budgetMin: 6000,
    budgetMax: 9000,
    timeline: "flexible",
    status: "completed",
    customerId: "cust-3",
    workerId: "work-5",
    completionPhotos: [
      "/placeholders/cleaning.png",
    ],
    completedAt: daysAgo(10),
    paymentStatus: "released",
    paymentAmount: 7500,
    platformFee: 1125,
    workerAmount: 6375,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(10),
  },
  {
    id: "task-6",
    title: "Build custom wardrobe for master bedroom",
    description:
      "Need a built-in wardrobe, approx 8ft wide x 7ft tall. Sliding doors preferred. Can share room measurements and reference photos.",
    category: "carpentry",
    photos: ["/placeholders/carpentry.png"],
    location: { address: "5 Negombo Rd", city: "Kadawatha, Gampaha", lat: 7.0058, lng: 79.9553 },
    budgetMin: 55000,
    budgetMax: 90000,
    timeline: "flexible",
    status: "open",
    customerId: "cust-2",
    completionPhotos: [],
    paymentStatus: "pending",
    paymentAmount: 0,
    platformFee: 0,
    workerAmount: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "task-7",
    title: "Weld new gate + side grill for boundary wall",
    description:
      "Need a new steel driveway gate (approx 10ft wide) and a matching side pedestrian gate. Simple design, primer + paint finish.",
    category: "welding",
    photos: [],
    location: { address: "31 Biyagama Rd", city: "Kelaniya, Colombo", lat: 6.9553, lng: 79.9219 },
    budgetMin: 30000,
    budgetMax: 45000,
    timeline: "flexible",
    status: "open",
    customerId: "cust-1",
    completionPhotos: [],
    paymentStatus: "pending",
    paymentAmount: 0,
    platformFee: 0,
    workerAmount: 0,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-8",
    title: "Garden cleanup and lawn mowing, monthly",
    description:
      "Medium-sized garden, needs mowing, hedge trimming and general tidy-up. Looking for someone reliable for a recurring monthly job.",
    category: "gardening",
    photos: ["/placeholders/gardening.png"],
    location: { address: "60 Pannipitiya Rd", city: "Battaramulla, Colombo", lat: 6.8988, lng: 79.9186 },
    budgetMin: 4000,
    budgetMax: 6000,
    timeline: "scheduled",
    scheduledDate: "2026-07-18",
    status: "open",
    customerId: "cust-3",
    completionPhotos: [],
    paymentStatus: "pending",
    paymentAmount: 0,
    platformFee: 0,
    workerAmount: 0,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: "task-9",
    title: "Repair washing machine, not spinning",
    description:
      "LG front-load washing machine fills with water but drum doesn't spin. Around 5 years old. Need a diagnosis and repair.",
    category: "appliance_repair",
    photos: [],
    location: { address: "45 Kirulapone Ave", city: "Nugegoda, Colombo", lat: 6.8721, lng: 79.8891 },
    budgetMin: 3000,
    budgetMax: 8000,
    timeline: "urgent",
    status: "disputed",
    customerId: "cust-1",
    workerId: "work-1",
    completionPhotos: [
      "/placeholders/appliance_repair.png",
    ],
    completedAt: daysAgo(4),
    paymentStatus: "escrow",
    paymentAmount: 5500,
    platformFee: 1100,
    workerAmount: 4400,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(3),
  },
  {
    id: "task-10",
    title: "Install 3 ceiling fans + check earthing",
    description:
      "Bought 3 new ceiling fans, need them installed in bedrooms. Also want the house earthing checked while you're here.",
    category: "electrical",
    photos: [],
    location: { address: "12 Lake Rd", city: "Kandy Town", lat: 7.2906, lng: 80.6337 },
    budgetMin: 5000,
    budgetMax: 9000,
    timeline: "flexible",
    status: "completed",
    customerId: "cust-2",
    workerId: "work-2",
    completionPhotos: [
      "/placeholders/electrical.png",
    ],
    completedAt: daysAgo(15),
    paymentStatus: "released",
    paymentAmount: 7000,
    platformFee: 1400,
    workerAmount: 5600,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(15),
  },
  {
    id: "task-11",
    title: "Assemble flatpack furniture (wardrobe + bed frame)",
    description:
      "Just bought flatpack furniture — one wardrobe and a queen bed frame. Need assembly, tools not required from your side.",
    category: "carpentry",
    photos: [],
    location: { address: "22 Havelock Rd", city: "Colombo 05", lat: 6.8862, lng: 79.8621 },
    budgetMin: 3500,
    budgetMax: 5500,
    timeline: "flexible",
    status: "open",
    customerId: "cust-1",
    completionPhotos: [],
    paymentStatus: "pending",
    paymentAmount: 0,
    platformFee: 0,
    workerAmount: 0,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "task-12",
    title: "Waterproof roof terrace before monsoon",
    description:
      "Open roof terrace has started leaking into the room below. Need waterproofing done properly before the next rains.",
    category: "painting",
    photos: ["/placeholders/painting.png"],
    location: { address: "78 Galle Rd", city: "Dehiwala, Colombo", lat: 6.8508, lng: 79.8654 },
    budgetMin: 20000,
    budgetMax: 35000,
    timeline: "urgent",
    status: "open",
    customerId: "cust-3",
    completionPhotos: [],
    paymentStatus: "pending",
    paymentAmount: 0,
    platformFee: 0,
    workerAmount: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
];

export const BIDS: Bid[] = [
  { id: "bid-1", taskId: "task-1", workerId: "work-1", offeredPrice: 2500, message: "Can come by this evening, I carry standard washers/cartridges in my van.", submittedAt: daysAgo(1), status: "pending" },
  { id: "bid-2", taskId: "task-2", workerId: "work-2", offeredPrice: 55000, message: "Happy to do a free inspection first, then a fixed quote. I'm EIE registered.", submittedAt: daysAgo(2), status: "pending" },
  { id: "bid-3", taskId: "task-3", workerId: "work-3", offeredPrice: 20000, message: "Can start Monday, will bring sample swatches for the colour consult.", submittedAt: daysAgo(5), status: "accepted" },
  { id: "bid-4", taskId: "task-4", workerId: "work-4", offeredPrice: 15000, message: "4-man crew, covered lorry, we've done plenty of no-lift moves.", submittedAt: daysAgo(4), status: "accepted" },
  { id: "bid-5", taskId: "task-6", workerId: "work-6", offeredPrice: 72000, message: "18 years doing built-ins, can share recent wardrobe photos for reference.", submittedAt: daysAgo(1), status: "pending" },
  { id: "bid-6", taskId: "task-6", workerId: "work-3", offeredPrice: 68000, message: "I mostly do painting but partner with a carpenter for combined jobs — can quote both together.", submittedAt: daysAgo(1), status: "pending" },
  { id: "bid-7", taskId: "task-7", workerId: "work-7", offeredPrice: 35000, message: "New to the platform but 3 years welding experience, can send photos of past gates.", submittedAt: daysAgo(1), status: "pending" },
  { id: "bid-8", taskId: "task-9", workerId: "work-1", offeredPrice: 5500, message: "Sounds like the drive belt or motor coupler, I'll bring parts for both.", submittedAt: daysAgo(8), status: "accepted" },
  { id: "bid-9", taskId: "task-10", workerId: "work-2", offeredPrice: 7000, message: "Can do all 3 fans plus an earthing check in one visit.", submittedAt: daysAgo(21), status: "accepted" },
  { id: "bid-10", taskId: "task-12", workerId: "work-3", offeredPrice: 28000, message: "I use a membrane + coating system, 5 year workmanship guarantee.", submittedAt: daysAgo(1), status: "pending" },
];

export const MESSAGES: Message[] = [
  { id: "msg-1", taskId: "task-3", fromUserId: "work-3", text: "Confirming — I'll paint the living room and hallway (~400 sq ft), 2 coats, crack filling included, for LKR 20,000.", attachments: [], timestamp: daysAgo(5) },
  { id: "msg-2", taskId: "task-3", fromUserId: "cust-3", text: "Yes, confirmed. See you Monday morning.", attachments: [], timestamp: daysAgo(5) },
  { id: "msg-3", taskId: "task-3", fromUserId: "cust-3", text: "Quick q — is that price for eggshell finish or matte?", attachments: [], timestamp: daysAgo(3) },
  { id: "msg-4", taskId: "task-3", fromUserId: "work-3", text: "Matte as standard, eggshell is +2,500 for the hallway only if you want easier-to-wipe walls there.", attachments: [], timestamp: daysAgo(3) },
  { id: "msg-5", taskId: "task-4", fromUserId: "work-4", text: "We're loading the lorry now, should be at your place in Malabe by 2pm.", attachments: [], timestamp: daysAgo(1) },
  { id: "msg-6", taskId: "task-4", fromUserId: "cust-1", text: "Great, I'll be there. Please be careful with the glass cabinet, it's fragile.", attachments: [], timestamp: daysAgo(1) },
  { id: "msg-7", taskId: "task-9", fromUserId: "cust-1", text: "This still isn't spinning properly, it's the same issue as before.", attachments: [], timestamp: daysAgo(4) },
  { id: "msg-8", taskId: "task-9", fromUserId: "work-1", text: "I replaced the belt like we discussed — can you send a video of it running so I can check the motor coupler too?", attachments: [], timestamp: daysAgo(3) },
];

export const RATINGS: Rating[] = [
  { id: "rat-1", taskId: "task-5", ratedById: "cust-3", ratedUserId: "work-5", ratingType: "worker", stars: 5, review: "Incredibly thorough, the kitchen looked brand new. Will book again.", categories: { communication: 5, professionalism: 5, quality: 5, timeliness: 5 }, createdAt: daysAgo(10) },
  { id: "rat-2", taskId: "task-10", ratedById: "cust-2", ratedUserId: "work-2", ratingType: "worker", stars: 5, review: "Very professional, explained the earthing issue clearly and fixed it on the spot.", categories: { communication: 5, professionalism: 5, quality: 5, timeliness: 4 }, createdAt: daysAgo(15) },
];

export const TRANSACTIONS: Transaction[] = [
  { id: "txn-1", taskId: "task-3", customerId: "cust-3", workerId: "work-3", amount: 20000, platformFee: 4000, workerAmount: 16000, status: "escrow", createdAt: daysAgo(5), escrowStartedAt: daysAgo(5) },
  { id: "txn-2", taskId: "task-4", customerId: "cust-1", workerId: "work-4", amount: 15000, platformFee: 3000, workerAmount: 12000, status: "escrow", createdAt: daysAgo(4), escrowStartedAt: daysAgo(4) },
  { id: "txn-3", taskId: "task-5", customerId: "cust-3", workerId: "work-5", amount: 7500, platformFee: 1125, workerAmount: 6375, status: "released", createdAt: daysAgo(18), escrowStartedAt: daysAgo(18), releasedAt: daysAgo(10) },
  { id: "txn-4", taskId: "task-9", customerId: "cust-1", workerId: "work-1", amount: 5500, platformFee: 1100, workerAmount: 4400, status: "escrow", createdAt: daysAgo(9), escrowStartedAt: daysAgo(9) },
  { id: "txn-5", taskId: "task-10", customerId: "cust-2", workerId: "work-2", amount: 7000, platformFee: 1400, workerAmount: 5600, status: "released", createdAt: daysAgo(22), escrowStartedAt: daysAgo(22), releasedAt: daysAgo(15) },
];

export const DISPUTES: Dispute[] = [
  {
    id: "disp-1",
    taskId: "task-9",
    customerId: "cust-1",
    workerId: "work-1",
    status: "reviewing",
    customerPhotos: [],
    customerDescription: "Machine still doesn't spin properly after the repair, same issue as reported.",
    workerExplanation: "Replaced the belt on-site; asked for a video to diagnose further but haven't received it yet.",
    workerPhotos: [],
    createdAt: daysAgo(3),
  },
];
